// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI9wSIlp65f6bgxvkH21dtHfHDEJacREY',
    appId: '1:843484696116:web:412179924435cd5071c461',
    messagingSenderId: '843484696116',
    projectId: 'instagramclone-c7084',
    authDomain: 'instagramclone-c7084.firebaseapp.com',
    storageBucket: 'instagramclone-c7084.appspot.com',
    measurementId: 'G-4GTKK3FJGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_x9chjGNaN93mvJ7bIeaBndQnHEE9-Os',
    appId: '1:843484696116:android:074f994ab7eeeae771c461',
    messagingSenderId: '843484696116',
    projectId: 'instagramclone-c7084',
    storageBucket: 'instagramclone-c7084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZDe7_PHeImXQ1uxaI0O2o0uWLi-MD5yI',
    appId: '1:843484696116:ios:dd1b36ac485a86f271c461',
    messagingSenderId: '843484696116',
    projectId: 'instagramclone-c7084',
    storageBucket: 'instagramclone-c7084.appspot.com',
    iosClientId: '843484696116-l98m995f99l5fsb8o947loormptdt4p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZDe7_PHeImXQ1uxaI0O2o0uWLi-MD5yI',
    appId: '1:843484696116:ios:a3cf0184fcc4188f71c461',
    messagingSenderId: '843484696116',
    projectId: 'instagramclone-c7084',
    storageBucket: 'instagramclone-c7084.appspot.com',
    iosClientId: '843484696116-qgqsf75i1bforvmscm9q4fdlmvfiomgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone.RunnerTests',
  );
}
